description: Curve left
constructor: duckietown_segmaps.get_map_curve
parameters:
  tile_size: 0.558 # outer white to outer white
  tile_spacing: 0.584
  width_yellow: 0.024
  width_white: 0.048
  gap_len: 0.024
  dash_len: 0.048
  direction: left
